# Imports

In [1]:
import numpy as np
import sys

sys.path.append("../../src")
sys.path.append("../palm-tree")

import embedder
import models

# Data

In [2]:
basic_block_a = [
    "mov rbp rdi",
    "mov ebx 0x1",
    "mov rdx rbx",
    "call memcpy",
    "mov [ rcx + rbx ] 0x0",
    "mov rcx rax",
    "mov [ rax ] 0x2e"
]

basic_block_b = [
    "push    rbp",
    "mov     rbp, rsp",
    "mov     DWORD PTR [rbp-4], 1",
    "mov     DWORD PTR [rbp-8], 2",
    "mov     eax, DWORD PTR [rbp-8]",
    "add     DWORD PTR [rbp-4], eax",
    "mov     eax, DWORD PTR [rbp-4]",
    "add     DWORD PTR [rbp-8], eax",
    "mov     eax, 0",
    "pop     rbp"
]

In [3]:
embedding_a = embedder.encode(basic_block_a)
embedding_b = embedder.encode(basic_block_b)

Loading Vocab C:/Users/thodo/Documents/σχολη/diplomatiki/PalmTree/pre-trained_model/palmtree/vocab
Vocab Size:  6631
Loading Vocab C:/Users/thodo/Documents/σχολη/diplomatiki/PalmTree/pre-trained_model/palmtree/vocab
Vocab Size:  6631


In [4]:
dataset = [basic_block_a, basic_block_b]

# LSTM Regression

In [7]:
from imp import reload


models=reload(models)

C:\Users\thodo\AppData\Local\Temp\ipykernel_8800\2390569962.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  from imp import reload


In [16]:
model = models.LSTM_Model(units = 128)
output = model(basic_block_a)

Loading Vocab C:/Users/thodo/Documents/σχολη/diplomatiki/PalmTree/pre-trained_model/palmtree/vocab
Vocab Size:  6631


In [15]:
output

<tf.Tensor: shape=(1, 7, 1), dtype=float32, numpy=
array([[[-0.14479099],
        [ 0.01299351],
        [-0.50360584],
        [-0.3273183 ],
        [-0.4774365 ],
        [-0.48631376],
        [-0.51076436]]], dtype=float32)>

In [17]:
output

<tf.Tensor: shape=(1, 7, 1), dtype=float32, numpy=
array([[[ 0.10528342],
        [ 0.56393456],
        [-0.1615681 ],
        [ 0.34888342],
        [ 0.00333524],
        [-0.00129151],
        [ 0.1782253 ]]], dtype=float32)>