# Imports

In [26]:
import tensorflow as tf
import numpy as np
import sys

sys.path.append("../../src")
sys.path.append("../palm-tree")

import embedder
import models

# Data

In [24]:
basic_block_a = [
    "mov rbp rdi",
    "mov ebx 0x1",
    "mov rdx rbx",
    "call memcpy",
    "mov [ rcx + rbx ] 0x0",
    "mov rcx rax",
    "mov [ rax ] 0x2e"
]

basic_block_b = [
    "push    rbp",
    "mov     rbp, rsp",
    "mov     DWORD PTR [rbp-4], 1",
    "mov     DWORD PTR [rbp-8], 2",
    "mov     eax, DWORD PTR [rbp-8]",
    "add     DWORD PTR [rbp-4], eax",
    "mov     eax, DWORD PTR [rbp-4]",
    "add     DWORD PTR [rbp-8], eax",
    "mov     eax, 0",
    "pop     rbp"
]

In [27]:
embedding_a = embedder.encode(basic_block_a)
embedding_b = embedder.encode(basic_block_b)

Loading Vocab C:/Users/thodo/Documents/σχολη/diplomatiki/PalmTree/pre-trained_model/palmtree/vocab
Vocab Size:  6631
Loading Vocab C:/Users/thodo/Documents/σχολη/diplomatiki/PalmTree/pre-trained_model/palmtree/vocab
Vocab Size:  6631


In [34]:
dataset = [embedding_a, embedding_b]

# LSTM Regression

In [41]:
model = models.LSTM_Model(units = 1)
output, state, seq = model(tf.expand_dims(embedding_a, 0))

In [42]:
output

<tf.Tensor: shape=(1, 7, 1), dtype=float32, numpy=
array([[[ 0.682158  ],
        [ 0.73212063],
        [ 0.8216771 ],
        [ 0.194113  ],
        [-0.20953073],
        [-0.020888  ],
        [-0.25502816]]], dtype=float32)>

In [43]:
state

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.25502816]], dtype=float32)>

In [44]:
seq

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.30452415]], dtype=float32)>